[package]
name = "sa430"
version = "0.1.0"
edition = "2021"

[target.x86_64-unknown-linux-gnu.dependencies]
udev = "0.9.1"

[dependencies]
clap = { version = "4.5.26", features = ["derive"] }

[dev-dependencies]
assert_cmd = "2.0.16"
predicates = "3.1.3"
